import { Medicine, MedicineCategory } from '../types/medicine';
import { Pharmacy } from '../types/pharmacy';
import { Address, User, NotificationItem } from '../types/user';

export const MOCK_CATEGORIES: MedicineCategory[] = [
  { id: 'cat-1', name: 'Pain & Fever', slug: 'pain-relief', iconName: 'fitness-outline', itemCount: 142, color: '#7C3AED' },
  { id: 'cat-2', name: 'Cold & Flu', slug: 'cold-flu', iconName: 'thermometer-outline', itemCount: 98, color: '#2563EB' },
  { id: 'cat-3', name: 'Diabetes Care', slug: 'diabetes', iconName: 'water-outline', itemCount: 86, color: '#D97706' },
  { id: 'cat-4', name: 'Vitamins & Immunity', slug: 'vitamins', iconName: 'sunny-outline', itemCount: 164, color: '#059669' },
  { id: 'cat-5', name: 'Stomach & Digestion', slug: 'digestive', iconName: 'heart-outline', itemCount: 115, color: '#DC2626' },
  { id: 'cat-6', name: 'Skin Care', slug: 'skin', iconName: 'sparkles-outline', itemCount: 120, color: '#DB2777' },
  { id: 'cat-7', name: 'Baby Care', slug: 'baby', iconName: 'happy-outline', itemCount: 74, color: '#0891B2' },
  { id: 'cat-8', name: 'Ayurvedic & Herbal', slug: 'ayurveda', iconName: 'leaf-outline', itemCount: 110, color: '#166534' },
  { id: 'cat-9', name: 'Heart & BP', slug: 'heart-bp', iconName: 'pulse-outline', itemCount: 92, color: '#B91C1C' },
];

export const MOCK_MEDICINES: Medicine[] = [
  // =========================================================================
  // 1. PAIN & FEVER / PAIN RELIEF (Category: pain-relief / pain-fever)
  // =========================================================================
  {
    id: 'med-1',
    name: 'Dolo 650 Tablet',
    brandName: 'Dolo',
    genericName: 'Paracetamol',
    saltComposition: 'Paracetamol (650mg)',
    manufacturer: 'Micro Labs Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Dolo 650 is an antipyretic and analgesic tablet used for fast relief from fever, headache, body ache, toothache, and post-vaccination fever.',
    uses: ['Fever', 'Headache', 'Body ache', 'Post-vaccination pyrexia', 'Muscle soreness'],
    sideEffects: ['Nausea (rare)', 'Allergic skin reaction (very rare)'],
    safetyAdvice: {
      pregnancy: 'Safe if prescribed by physician.',
      breastfeeding: 'Safe to use during breastfeeding.',
      driving: 'Does not impair driving.',
      alcohol: 'Avoid alcohol as it increases liver strain.',
    },
    mrp: 34.0,
    discountPrice: 28.5,
    discountPercentage: 16,
    rxRequired: false,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 450,
    rating: 4.8,
    reviewCount: 4120,
    alternatives: [
      { id: 'alt-1', name: 'Crocin 650 Advance', brandName: 'Crocin', manufacturer: 'GlaxoSmithKline', mrp: 35.0, savingsPercentage: 14, saltComposition: 'Paracetamol (650mg)', rxRequired: false },
      { id: 'alt-2', name: 'Pacimol 650 Tablet', brandName: 'Pacimol', manufacturer: 'Ipca Laboratories', mrp: 24.0, savingsPercentage: 29, saltComposition: 'Paracetamol (650mg)', rxRequired: false },
    ],
  },
  {
    id: 'med-2',
    name: 'Crocin 650 Advance Tablet',
    brandName: 'Crocin',
    genericName: 'Paracetamol',
    saltComposition: 'Paracetamol (650mg) with Optizorb Technology',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Crocin 650 Advance features Optizorb technology for fast absorption within 5 minutes, relieving severe fever and pain.',
    uses: ['High fever', 'Headache', 'Backache', 'Joint pain'],
    sideEffects: ['Mild gastric irritation (rare)'],
    safetyAdvice: {
      pregnancy: 'Safe when taken as advised.',
      breastfeeding: 'Safe in therapeutic doses.',
      driving: 'No drowsiness caused.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 35.0,
    discountPrice: 30.0,
    discountPercentage: 14,
    rxRequired: false,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 380,
    rating: 4.7,
    reviewCount: 2890,
  },
  {
    id: 'med-3',
    name: 'Combiflam Tablet',
    brandName: 'Combiflam',
    genericName: 'Ibuprofen + Paracetamol',
    saltComposition: 'Ibuprofen (400mg) + Paracetamol (325mg)',
    manufacturer: 'Sanofi India Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Combiflam combines the anti-inflammatory power of Ibuprofen with the fever-reducing power of Paracetamol.',
    uses: ['Dental pain', 'Muscle spasms', 'Joint inflammation', 'Arthritic pain', 'Fever'],
    sideEffects: ['Heartburn', 'Nausea', 'Dizziness'],
    safetyAdvice: {
      pregnancy: 'Not recommended in 3rd trimester.',
      breastfeeding: 'Consult doctor before use.',
      driving: 'May cause mild drowsiness.',
      alcohol: 'Increases risk of stomach ulceration.',
    },
    mrp: 48.0,
    discountPrice: 41.5,
    discountPercentage: 14,
    rxRequired: false,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Strip of 20 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 520,
    rating: 4.7,
    reviewCount: 3100,
  },
  {
    id: 'med-4',
    name: 'Meftal-Spas Tablet',
    brandName: 'Meftal-Spas',
    genericName: 'Mefenamic Acid + Dicyclomine',
    saltComposition: 'Mefenamic Acid (250mg) + Dicyclomine Hydrochloride (10mg)',
    manufacturer: 'Blue Cross Laboratories Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Meftal-Spas relieves abdominal cramp, menstrual spasms, and gastrointestinal colic pain.',
    uses: ['Menstrual cramps', 'Stomach colic pain', 'Spasmodic intestinal pain'],
    sideEffects: ['Dry mouth', 'Drowsiness', 'Nausea'],
    safetyAdvice: {
      pregnancy: 'Use only under strict medical supervision.',
      breastfeeding: 'Consult physician.',
      driving: 'Caution: causes drowsiness.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 56.0,
    discountPrice: 48.0,
    discountPercentage: 14,
    rxRequired: true,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Strip of 10 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 290,
    rating: 4.8,
    reviewCount: 1950,
  },
  {
    id: 'med-5',
    name: 'Volini Pain Relief Gel',
    brandName: 'Volini',
    genericName: 'Diclofenac + Linseed Oil + Menthol',
    saltComposition: 'Diclofenac Diethylamine (1.16%) + Linseed Oil (3%) + Methyl Salicylate (10%) + Menthol (5%)',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Volini Gel penetrates deep into muscle tissues to provide instant relief from sprains, backache, neck pain, and joint stiffness.',
    uses: ['Backache', 'Neck & shoulder pain', 'Sprains & strains', 'Knee joint pain'],
    sideEffects: ['Skin redness (temporary)', 'Tingling sensation'],
    safetyAdvice: {
      pregnancy: 'Safe for localized external application.',
      breastfeeding: 'Safe for external use.',
      driving: 'No effect.',
      alcohol: 'No interaction.',
    },
    mrp: 160.0,
    discountPrice: 135.0,
    discountPercentage: 16,
    rxRequired: false,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Tube of 30g',
    isPopular: true,
    inStock: true,
    stockCount: 340,
    rating: 4.8,
    reviewCount: 3800,
  },
  {
    id: 'med-6',
    name: 'Saridon Headache Relief Tablet',
    brandName: 'Saridon',
    genericName: 'Paracetamol + Propyphenazone + Caffeine',
    saltComposition: 'Paracetamol (250mg) + Propyphenazone (150mg) + Caffeine (50mg)',
    manufacturer: 'Piramal Pharma Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Saridon is a triple-action formula providing rapid relief from severe headaches in under 15 minutes.',
    uses: ['Tension headache', 'Migraine pain', 'Toothache', 'Neuralgia'],
    sideEffects: ['Restlessness (due to caffeine)', 'Mild insomnia if taken late'],
    safetyAdvice: {
      pregnancy: 'Consult doctor.',
      breastfeeding: 'Consult doctor.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 48.0,
    discountPrice: 42.0,
    discountPercentage: 12,
    rxRequired: false,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Strip of 10 tablets',
    isPopular: false,
    inStock: true,
    stockCount: 410,
    rating: 4.6,
    reviewCount: 2450,
  },

  // =========================================================================
  // 2. COLD, COUGH & FLU (Category: cold-flu / cold-cough)
  // =========================================================================
  {
    id: 'med-7',
    name: 'Cheston Cold Tablet',
    brandName: 'Cheston Cold',
    genericName: 'Cetirizine + Paracetamol + Phenylephrine',
    saltComposition: 'Cetirizine (5mg) + Paracetamol (325mg) + Phenylephrine (10mg)',
    manufacturer: 'Cipla Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Cheston Cold relieves symptoms of common cold such as runny nose, sneezing, congestion, fever, and watery eyes.',
    uses: ['Common cold', 'Runny nose & sneezing', 'Nasal congestion', 'Sinus headache'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Fatigue'],
    safetyAdvice: {
      pregnancy: 'Consult doctor before use.',
      breastfeeding: 'Not recommended without doctor guidance.',
      driving: 'Avoid driving: causes drowsiness.',
      alcohol: 'Avoid alcohol: increases sedation.',
    },
    mrp: 52.0,
    discountPrice: 45.0,
    discountPercentage: 13,
    rxRequired: false,
    category: 'Cold & Flu',
    categorySlug: 'cold-flu',
    packForm: 'Strip of 10 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 460,
    rating: 4.7,
    reviewCount: 3200,
  },
  {
    id: 'med-8',
    name: 'Ascoril D Plus Cough Syrup',
    brandName: 'Ascoril',
    genericName: 'Dextromethorphan + Chlorpheniramine + Phenylephrine',
    saltComposition: 'Dextromethorphan (10mg) + Chlorpheniramine (2mg) + Phenylephrine (5mg) / 5ml',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Ascoril D Plus is a sugar-free dry cough syrup that soothes throat tickles and suppresses persistent dry cough.',
    uses: ['Dry irritating cough', 'Allergic throat tickle', 'Nasal congestion'],
    sideEffects: ['Sleepiness', 'Mild dizziness', 'Nausea'],
    safetyAdvice: {
      pregnancy: 'Consult doctor.',
      breastfeeding: 'Consult doctor.',
      driving: 'Causes mild drowsiness.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 138.0,
    discountPrice: 118.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Cold & Flu',
    categorySlug: 'cold-flu',
    packForm: 'Bottle of 100ml',
    isPopular: true,
    inStock: true,
    stockCount: 280,
    rating: 4.8,
    reviewCount: 2750,
  },
  {
    id: 'med-9',
    name: 'Otrivin Oxy Fast Relief Nasal Spray',
    brandName: 'Otrivin',
    genericName: 'Oxymetazoline Hydrochloride',
    saltComposition: 'Oxymetazoline Hydrochloride (0.05% w/v)',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Otrivin Oxy unblocks nasal passages in just 25 seconds and provides breathing relief for up to 12 hours.',
    uses: ['Blocked nose', 'Sinus congestion', 'Allergic rhinitis'],
    sideEffects: ['Nasal stinging (temporary)', 'Dry nose'],
    safetyAdvice: {
      pregnancy: 'Safe for short-term use (max 5 days).',
      breastfeeding: 'Safe.',
      driving: 'No impairment.',
      alcohol: 'No interaction.',
    },
    mrp: 115.0,
    discountPrice: 98.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Cold & Flu',
    categorySlug: 'cold-flu',
    packForm: 'Bottle of 10ml',
    isPopular: true,
    inStock: true,
    stockCount: 390,
    rating: 4.8,
    reviewCount: 4200,
  },
  {
    id: 'med-10',
    name: 'Cofsils Herbal Cough Lozenges (Ginger Lemon)',
    brandName: 'Cofsils',
    genericName: 'Amylmetacresol + Dichlorobenzyl Alcohol',
    saltComposition: 'Amylmetacresol (0.6mg) + 2,4-Dichlorobenzyl Alcohol (1.2mg)',
    manufacturer: 'Cipla Health Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Cofsils provides quick soothing relief from sore throat, throat pain, and hoarseness of voice.',
    uses: ['Sore throat', 'Throat infection', 'Pain during swallowing'],
    sideEffects: ['None reported'],
    safetyAdvice: {
      pregnancy: 'Safe.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 38.0,
    discountPrice: 32.0,
    discountPercentage: 16,
    rxRequired: false,
    category: 'Cold & Flu',
    categorySlug: 'cold-flu',
    packForm: 'Strip of 10 lozenges',
    isPopular: false,
    inStock: true,
    stockCount: 650,
    rating: 4.7,
    reviewCount: 1800,
  },

  // =========================================================================
  // 3. DIABETES CARE (Category: diabetes)
  // =========================================================================
  {
    id: 'med-11',
    name: 'Glycomet GP 1 Tablet PR',
    brandName: 'Glycomet',
    genericName: 'Glimepiride + Metformin',
    saltComposition: 'Glimepiride (1mg) + Metformin Hydrochloride (500mg)',
    manufacturer: 'USV Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Glycomet GP 1 PR is an oral anti-diabetic medicine used to control high blood sugar in type 2 diabetes mellitus.',
    uses: ['Type 2 Diabetes Mellitus', 'Glycemic control'],
    sideEffects: ['Hypoglycemia (low blood sugar)', 'Nausea', 'Metallic taste'],
    safetyAdvice: {
      pregnancy: 'Not recommended; insulin preferred.',
      breastfeeding: 'Consult doctor.',
      driving: 'Caution: risk of low blood sugar while driving.',
      alcohol: 'Avoid alcohol: severe hypoglycemia risk.',
    },
    mrp: 135.0,
    discountPrice: 115.0,
    discountPercentage: 15,
    rxRequired: true,
    category: 'Diabetes Care',
    categorySlug: 'diabetes',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 310,
    rating: 4.8,
    reviewCount: 2900,
  },
  {
    id: 'med-12',
    name: 'Janumet 50mg/500mg Tablet',
    brandName: 'Janumet',
    genericName: 'Sitagliptin + Metformin',
    saltComposition: 'Sitagliptin (50mg) + Metformin Hydrochloride (500mg)',
    manufacturer: 'MSD Pharmaceuticals Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Janumet combines a DPP-4 inhibitor (Sitagliptin) with Metformin for comprehensive 24-hour blood glucose control.',
    uses: ['Type 2 Diabetes Mellitus with high HbA1c'],
    sideEffects: ['Upper respiratory infection', 'Headache', 'Diarrhea'],
    safetyAdvice: {
      pregnancy: 'Consult doctor.',
      breastfeeding: 'Consult doctor.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 350.0,
    discountPrice: 298.0,
    discountPercentage: 15,
    rxRequired: true,
    category: 'Diabetes Care',
    categorySlug: 'diabetes',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 220,
    rating: 4.9,
    reviewCount: 1600,
  },
  {
    id: 'med-13',
    name: 'Accu-Chek Active Glucose Test Strips (50s)',
    brandName: 'Accu-Chek',
    genericName: 'Blood Glucose Test Strips',
    saltComposition: 'Electrochemical Glucose Dehydrogenase Biosensor Strips',
    manufacturer: 'Roche Diabetes Care India',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Accu-Chek Active test strips provide accurate capillary blood glucose readings in just 5 seconds for self-monitoring.',
    uses: ['Blood glucose self-testing at home'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'Safe for gestational diabetes monitoring.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 1049.0,
    discountPrice: 899.0,
    discountPercentage: 14,
    rxRequired: false,
    category: 'Diabetes Care',
    categorySlug: 'diabetes',
    packForm: 'Box of 50 strips',
    isPopular: true,
    inStock: true,
    stockCount: 180,
    rating: 4.9,
    reviewCount: 4800,
  },

  // =========================================================================
  // 4. VITAMINS, MINERALS & IMMUNITY (Category: vitamins)
  // =========================================================================
  {
    id: 'med-14',
    name: 'Becosules Z Capsule',
    brandName: 'Becosules',
    genericName: 'B-Complex + Vitamin C + Zinc',
    saltComposition: 'Vitamin B-Complex (B1, B2, B3, B6, B12) + Vitamin C (50mg) + Zinc Sulphate (41.4mg)',
    manufacturer: 'Pfizer Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Becosules Z cures mouth ulcers, boosts immunity, enhances tissue repair, and replenishes essential B-vitamins.',
    uses: ['Mouth ulcers', 'Vitamin deficiency', 'General weakness', 'Immunity support'],
    sideEffects: ['Bright yellow urine (harmless Vitamin B2 excretion)'],
    safetyAdvice: {
      pregnancy: 'Safe supplement.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 55.0,
    discountPrice: 48.0,
    discountPercentage: 13,
    rxRequired: false,
    category: 'Vitamins',
    categorySlug: 'vitamins',
    packForm: 'Strip of 20 capsules',
    isPopular: true,
    inStock: true,
    stockCount: 580,
    rating: 4.8,
    reviewCount: 5200,
  },
  {
    id: 'med-15',
    name: 'Shelcal 500 Calcium Tablet',
    brandName: 'Shelcal',
    genericName: 'Calcium + Vitamin D3',
    saltComposition: 'Elemental Calcium (500mg) + Vitamin D3 (250 IU)',
    manufacturer: 'Torrent Pharmaceuticals Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Shelcal 500 strengthens bones and teeth, prevents osteoporosis, and fulfills daily calcium requirements for adults.',
    uses: ['Bone strength', 'Osteoporosis prevention', 'Joint stiffness', 'Pregnancy calcium support'],
    sideEffects: ['Constipation (mild)', 'Bloating'],
    safetyAdvice: {
      pregnancy: 'Recommended daily calcium supplement.',
      breastfeeding: 'Safe and recommended.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 140.0,
    discountPrice: 118.0,
    discountPercentage: 16,
    rxRequired: false,
    category: 'Vitamins',
    categorySlug: 'vitamins',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 420,
    rating: 4.8,
    reviewCount: 3900,
  },
  {
    id: 'med-16',
    name: 'Limcee 500mg Chewable Vitamin C',
    brandName: 'Limcee',
    genericName: 'Ascorbic Acid / Vitamin C',
    saltComposition: 'Ascorbic Acid (100mg) + Sodium Ascorbate (450mg)',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Limcee is an orange-flavored chewable Vitamin C tablet that acts as a strong antioxidant, boosting immune resistance against infections.',
    uses: ['Immunity booster', 'Skin radiance', 'Wound healing', 'Cold prevention'],
    sideEffects: ['None in normal dosage'],
    safetyAdvice: {
      pregnancy: 'Safe.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 28.0,
    discountPrice: 24.0,
    discountPercentage: 14,
    rxRequired: false,
    category: 'Vitamins',
    categorySlug: 'vitamins',
    packForm: 'Strip of 15 chewable tablets',
    isPopular: true,
    inStock: true,
    stockCount: 710,
    rating: 4.7,
    reviewCount: 4600,
  },
  {
    id: 'med-17',
    name: 'Evion 400mg Vitamin E Capsule',
    brandName: 'Evion',
    genericName: 'Tocopheryl Acetate / Vitamin E',
    saltComposition: 'Tocopheryl Acetate (400mg)',
    manufacturer: 'Procter & Gamble Hygiene and Health Care Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Evion 400 contains active Vitamin E for skin nourishment, hair growth, muscle cramps, and cellular antioxidant defense.',
    uses: ['Healthy skin & hair', 'Muscle cramps', 'Antioxidant support'],
    sideEffects: ['Nausea if taken on empty stomach'],
    safetyAdvice: {
      pregnancy: 'Safe when prescribed.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 42.0,
    discountPrice: 35.0,
    discountPercentage: 17,
    rxRequired: false,
    category: 'Vitamins',
    categorySlug: 'vitamins',
    packForm: 'Strip of 10 green softgels',
    isPopular: true,
    inStock: true,
    stockCount: 620,
    rating: 4.8,
    reviewCount: 5100,
  },

  // =========================================================================
  // 5. STOMACH & DIGESTION (Category: digestive / digestion)
  // =========================================================================
  {
    id: 'med-18',
    name: 'Pan-D Capsule SR',
    brandName: 'Pan-D',
    genericName: 'Pantoprazole + Domperidone',
    saltComposition: 'Pantoprazole (40mg) + Domperidone (30mg SR)',
    manufacturer: 'Alkem Laboratories Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Pan-D relieves acidity, heartburn, gastroesophageal reflux disease (GERD), gas, and nausea.',
    uses: ['Acid reflux & GERD', 'Heartburn', 'Nausea associated with acidity', 'Peptic ulcer'],
    sideEffects: ['Dry mouth', 'Headache', 'Dizziness'],
    safetyAdvice: {
      pregnancy: 'Consult doctor before taking.',
      breastfeeding: 'Consult doctor.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 218.0,
    discountPrice: 185.0,
    discountPercentage: 15,
    rxRequired: true,
    category: 'Digestive Care',
    categorySlug: 'digestive',
    packForm: 'Strip of 15 capsules',
    isPopular: true,
    inStock: true,
    stockCount: 480,
    rating: 4.8,
    reviewCount: 4200,
  },
  {
    id: 'med-19',
    name: 'Digene Gel Antacid (Mint Flavour)',
    brandName: 'Digene',
    genericName: 'Magnesium Hydroxide + Aluminium Hydroxide + Simethicone',
    saltComposition: 'Magnesium Hydroxide (25mg) + Dried Aluminium Hydroxide (300mg) + Simethicone (25mg) / 5ml',
    manufacturer: 'Abbott India Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Digene Gel provides instant cooling relief from stomach burning, gas, bloating, and hyperacidity.',
    uses: ['Heartburn', 'Gas & bloating', 'Stomach burning', 'Indigestion'],
    sideEffects: ['Chalky taste', 'Mild constipation or loose stools'],
    safetyAdvice: {
      pregnancy: 'Safe for occasional acidity.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 170.0,
    discountPrice: 145.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Digestive Care',
    categorySlug: 'digestive',
    packForm: 'Bottle of 200ml',
    isPopular: true,
    inStock: true,
    stockCount: 350,
    rating: 4.8,
    reviewCount: 3100,
  },
  {
    id: 'med-20',
    name: 'Cremaffin Plus Syrup (Sugar Free)',
    brandName: 'Cremaffin',
    genericName: 'Liquid Paraffin + Milk of Magnesia + Sodium Picosulfate',
    saltComposition: 'Liquid Paraffin (3.75ml) + Milk of Magnesia (11.25ml) + Sodium Picosulfate (3.33mg) / 15ml',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Cremaffin Plus is a gentle bowel regulator that provides overnight relief from severe chronic constipation.',
    uses: ['Chronic constipation', 'Piles/fissure pain relief during defecation'],
    sideEffects: ['Abdominal cramps if overdosed'],
    safetyAdvice: {
      pregnancy: 'Consult doctor.',
      breastfeeding: 'Consult doctor.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 285.0,
    discountPrice: 245.0,
    discountPercentage: 14,
    rxRequired: false,
    category: 'Digestive Care',
    categorySlug: 'digestive',
    packForm: 'Bottle of 225ml',
    isPopular: false,
    inStock: true,
    stockCount: 190,
    rating: 4.7,
    reviewCount: 1400,
  },

  // =========================================================================
  // 6. SKIN CARE & DERMATOLOGY (Category: skin / skin-care)
  // =========================================================================
  {
    id: 'med-21',
    name: 'Candid-B Anti-Fungal Cream',
    brandName: 'Candid-B',
    genericName: 'Clotrimazole + Beclomethasone',
    saltComposition: 'Clotrimazole (1% w/w) + Beclomethasone Dipropionate (0.025% w/w)',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Candid-B treats fungal skin infections accompanied by inflammation, severe itching, and redness (ringworm, sweat rash, jock itch).',
    uses: ['Fungal skin infection', 'Ringworm (Tinea)', 'Severe itching and skin redness'],
    sideEffects: ['Mild burning or stinging at application site'],
    safetyAdvice: {
      pregnancy: 'Safe for external application under doctor advice.',
      breastfeeding: 'Do not apply on breast area.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 168.0,
    discountPrice: 142.0,
    discountPercentage: 15,
    rxRequired: true,
    category: 'Skin Care',
    categorySlug: 'skin',
    packForm: 'Tube of 20g',
    isPopular: true,
    inStock: true,
    stockCount: 320,
    rating: 4.8,
    reviewCount: 2800,
  },
  {
    id: 'med-22',
    name: 'Betadine 10% Antiseptic Ointment',
    brandName: 'Betadine',
    genericName: 'Povidone Iodine',
    saltComposition: 'Povidone Iodine (10% w/w)',
    manufacturer: 'Win-Medicare Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Betadine is a microbicidal antiseptic ointment for quick healing and infection prevention in cuts, burns, wounds, and abrasions.',
    uses: ['Cuts & wounds', 'Minor burns', 'Surgical dressing', 'Skin infection prevention'],
    sideEffects: ['Skin staining (washes off)'],
    safetyAdvice: {
      pregnancy: 'Safe for small wounds.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 130.0,
    discountPrice: 110.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Skin Care',
    categorySlug: 'skin',
    packForm: 'Tube of 20g',
    isPopular: true,
    inStock: true,
    stockCount: 460,
    rating: 4.9,
    reviewCount: 4100,
  },
  {
    id: 'med-23',
    name: 'Boroline Antiseptic Ayurvedic Cream',
    brandName: 'Boroline',
    genericName: 'Boric Acid + Zinc Oxide + Lanolin',
    saltComposition: 'Boric Acid + Zinc Oxide + Anhydrous Lanolin',
    manufacturer: 'G.D. Pharmaceuticals Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Boroline heals dry cracked lips, rough elbows, cracked heels, minor cuts, and chapped skin overnight.',
    uses: ['Cracked heels', 'Chapped lips', 'Dry skin healing', 'Minor skin cracks'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'Safe Ayurvedic product.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 48.0,
    discountPrice: 42.0,
    discountPercentage: 12,
    rxRequired: false,
    category: 'Skin Care',
    categorySlug: 'skin',
    packForm: 'Tub of 40g',
    isPopular: false,
    inStock: true,
    stockCount: 510,
    rating: 4.8,
    reviewCount: 3900,
  },

  // =========================================================================
  // 7. BABY CARE (Category: baby)
  // =========================================================================
  {
    id: 'med-24',
    name: "Woodward's Gripe Water",
    brandName: "Woodward's",
    genericName: 'Dill Oil + Sarjikakshara',
    saltComposition: 'Dill Oil (0.005ml) + Sarjikakshara (0.05g) / 5ml',
    manufacturer: 'TTK Healthcare Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: "Woodward's Gripe Water relieves infant colic, tummy gas, griping pain, and acidity during the teething period.",
    uses: ['Infant colic pain', 'Tummy gas & griping', 'Teething distress'],
    sideEffects: ['None reported'],
    safetyAdvice: {
      pregnancy: 'For infant use.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Alcohol-free formula.',
    },
    mrp: 70.0,
    discountPrice: 62.0,
    discountPercentage: 11,
    rxRequired: false,
    category: 'Baby Care',
    categorySlug: 'baby',
    packForm: 'Bottle of 130ml',
    isPopular: true,
    inStock: true,
    stockCount: 340,
    rating: 4.8,
    reviewCount: 2900,
  },
  {
    id: 'med-25',
    name: 'Himalaya Baby Massage Oil',
    brandName: 'Himalaya',
    genericName: 'Olive Oil + Winter Cherry (Ashvagandha)',
    saltComposition: 'Olive Oil + Country Mallow + Winter Cherry (Ashvagandha)',
    manufacturer: 'Himalaya Wellness Company',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Himalaya Baby Massage Oil improves infant bone and muscle tone, keeping baby delicate skin soft, supple, and glowing.',
    uses: ['Daily infant massage', 'Muscle & bone development', 'Skin nourishment'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'Safe.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 210.0,
    discountPrice: 175.0,
    discountPercentage: 17,
    rxRequired: false,
    category: 'Baby Care',
    categorySlug: 'baby',
    packForm: 'Bottle of 200ml',
    isPopular: true,
    inStock: true,
    stockCount: 260,
    rating: 4.9,
    reviewCount: 3300,
  },
  {
    id: 'med-26',
    name: 'Himalaya Bonnisan Drops',
    brandName: 'Bonnisan',
    genericName: 'Dill Oil + Cardamom + Tinospora',
    saltComposition: 'Shatapushpa (Dill) + Ela (Cardamom) + Guduchi extracts',
    manufacturer: 'Himalaya Wellness Company',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Bonnisan is an Ayurvedic digestive tonic that promotes healthy digestion, appetite, and weight gain in infants.',
    uses: ['Infant indigestion', 'Poor appetite in babies', 'Colic and gas'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'For pediatric use.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 95.0,
    discountPrice: 85.0,
    discountPercentage: 11,
    rxRequired: false,
    category: 'Baby Care',
    categorySlug: 'baby',
    packForm: 'Bottle of 30ml with dropper',
    isPopular: false,
    inStock: true,
    stockCount: 190,
    rating: 4.7,
    reviewCount: 1200,
  },

  // =========================================================================
  // 8. AYURVEDIC & HERBAL MEDICINES (Category: ayurveda / herbal)
  // =========================================================================
  {
    id: 'med-27',
    name: 'Dabur Chyawanprash (2X Immunity)',
    brandName: 'Dabur',
    genericName: 'Amla + 40+ Ayurvedic Rasayana Herbs',
    saltComposition: 'Emblica Officinalis (Amla) + Withania Somnifera (Ashwagandha) + Pippali + Guduchi',
    manufacturer: 'Dabur India Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Dabur Chyawanprash doubles internal immunity against seasonal infections, enhances stamina, and supports respiratory health.',
    uses: ['Immunity building', 'Cold and cough protection', 'Energy & stamina booster'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'Safe Ayurvedic supplement.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 450.0,
    discountPrice: 385.0,
    discountPercentage: 14,
    rxRequired: false,
    category: 'Ayurvedic',
    categorySlug: 'ayurveda',
    packForm: 'Jar of 1kg',
    isPopular: true,
    inStock: true,
    stockCount: 290,
    rating: 4.9,
    reviewCount: 6400,
  },
  {
    id: 'med-28',
    name: 'Himalaya Liv.52 Herbal Liver Tablet',
    brandName: 'Liv.52',
    genericName: 'Caper Bush (Himsra) + Wild Chicory (Kasani)',
    saltComposition: 'Himsra (Capparis spinosa) + Kasani (Cichorium intybus) + Mandur bhasma',
    manufacturer: 'Himalaya Wellness Company',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Liv.52 protects the liver against toxins, enhances metabolic appetite, and accelerates recovery from fatty liver and jaundice.',
    uses: ['Liver protection & detox', 'Appetite loss', 'Fatty liver support', 'Digestion improvement'],
    sideEffects: ['None reported in recommended doses'],
    safetyAdvice: {
      pregnancy: 'Safe Ayurvedic liver tonic.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Protecting against alcoholic liver injury.',
    },
    mrp: 170.0,
    discountPrice: 145.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Ayurvedic',
    categorySlug: 'ayurveda',
    packForm: 'Bottle of 100 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 480,
    rating: 4.8,
    reviewCount: 5100,
  },
  {
    id: 'med-29',
    name: 'Dabur Honitus Herbal Cough Syrup',
    brandName: 'Honitus',
    genericName: 'Tulsi + Mulethi + Banapsha + Honey',
    saltComposition: 'Ocimum Sanctum (Tulsi) + Glycyrrhiza Glabra (Mulethi) + Pure Honey',
    manufacturer: 'Dabur India Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Dabur Honitus is a 100% non-drowsy Ayurvedic cough syrup enriched with honey and tulsi that effectively cures productive and dry cough.',
    uses: ['Cough relief without sleepiness', 'Throat irritation', 'Allergic bronchitis'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'Safe herbal syrup.',
      breastfeeding: 'Safe.',
      driving: 'Safe: 100% non-drowsy.',
      alcohol: 'Safe.',
    },
    mrp: 120.0,
    discountPrice: 105.0,
    discountPercentage: 13,
    rxRequired: false,
    category: 'Ayurvedic',
    categorySlug: 'ayurveda',
    packForm: 'Bottle of 100ml',
    isPopular: false,
    inStock: true,
    stockCount: 360,
    rating: 4.7,
    reviewCount: 2200,
  },

  // =========================================================================
  // 9. HEART & BP (Category: heart-bp / cardiac)
  // =========================================================================
  {
    id: 'med-30',
    name: 'Telma 40 Blood Pressure Tablet',
    brandName: 'Telma',
    genericName: 'Telmisartan',
    saltComposition: 'Telmisartan (40mg)',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Telma 40 is an angiotensin receptor blocker (ARB) used to lower high blood pressure and reduce the risk of stroke and heart attack.',
    uses: ['Hypertension (High Blood Pressure)', 'Cardiovascular risk reduction in adults'],
    sideEffects: ['Dizziness', 'Sinus congestion', 'Back pain'],
    safetyAdvice: {
      pregnancy: 'Strictly contraindicated in pregnancy.',
      breastfeeding: 'Consult doctor.',
      driving: 'Caution: may cause dizziness initially.',
      alcohol: 'Avoid alcohol as it excessively lowers blood pressure.',
    },
    mrp: 230.0,
    discountPrice: 195.0,
    discountPercentage: 15,
    rxRequired: true,
    category: 'Heart & BP',
    categorySlug: 'heart-bp',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 310,
    rating: 4.8,
    reviewCount: 3400,
  },
  {
    id: 'med-31',
    name: 'Amlong 5mg Tablet',
    brandName: 'Amlong',
    genericName: 'Amlodipine',
    saltComposition: 'Amlodipine Besylate (5mg)',
    manufacturer: 'Micro Labs Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Amlong 5 relaxes blood vessels, improving blood flow and reducing heart workload in hypertension and angina.',
    uses: ['High blood pressure', 'Angina (chest pain)'],
    sideEffects: ['Ankle swelling', 'Headache', 'Flushing'],
    safetyAdvice: {
      pregnancy: 'Consult doctor.',
      breastfeeding: 'Consult doctor.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 58.0,
    discountPrice: 48.0,
    discountPercentage: 17,
    rxRequired: true,
    category: 'Heart & BP',
    categorySlug: 'heart-bp',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 390,
    rating: 4.8,
    reviewCount: 2700,
  },

  // =========================================================================
  // TOP PHARMACEUTICAL BRANDS (Cipla, Sun Pharma, Abbott, Dr. Reddy's, Himalaya, Mankind)
  // =========================================================================
  // --- 1. CIPLA HEALTH & PHARMA ---
  {
    id: 'med-cip-1',
    name: 'Asthalin 100mcg Inhaler',
    brandName: 'Asthalin',
    genericName: 'Salbutamol',
    saltComposition: 'Salbutamol (100mcg/actuation)',
    manufacturer: 'Cipla Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Asthalin Inhaler is a bronchodilator that relaxes the muscles in the airways and increases airflow to the lungs for fast relief in asthma and COPD.',
    uses: ['Asthma flare-ups', 'Shortness of breath', 'Wheezing', 'COPD'],
    sideEffects: ['Tremors (mild)', 'Headache (rare)', 'Palpitations'],
    safetyAdvice: {
      pregnancy: 'Consult doctor before use.',
      breastfeeding: 'Safe under medical supervision.',
      driving: 'No drowsiness caused.',
      alcohol: 'No direct interaction.',
    },
    mrp: 172.0,
    discountPrice: 148.0,
    discountPercentage: 14,
    rxRequired: true,
    category: 'Cold & Flu',
    categorySlug: 'cold-flu',
    packForm: 'Inhaler of 200 metered doses',
    isPopular: true,
    inStock: true,
    stockCount: 180,
    rating: 4.9,
    reviewCount: 3200,
  },
  {
    id: 'med-cip-2',
    name: 'Montair LC Tablet',
    brandName: 'Montair LC',
    genericName: 'Montelukast + Levocetirizine',
    saltComposition: 'Montelukast (10mg) + Levocetirizine (5mg)',
    manufacturer: 'Cipla Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Montair LC Tablet is an anti-allergic combination medication used to treat allergic rhinitis, seasonal allergies, sneezing, and runny nose.',
    uses: ['Allergic rhinitis', 'Sneezing', 'Watery eyes', 'Chronic urticaria'],
    sideEffects: ['Drowsiness (mild)', 'Dry mouth'],
    safetyAdvice: {
      pregnancy: 'Use only when prescribed.',
      breastfeeding: 'Consult doctor before use.',
      driving: 'Caution: may cause slight drowsiness.',
      alcohol: 'Avoid alcohol while taking anti-allergics.',
    },
    mrp: 220.0,
    discountPrice: 185.0,
    discountPercentage: 16,
    rxRequired: true,
    category: 'Cold & Flu',
    categorySlug: 'cold-flu',
    packForm: 'Strip of 10 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 290,
    rating: 4.8,
    reviewCount: 2450,
  },
  {
    id: 'med-cip-3',
    name: 'Omnigel Pain Relief Spray (55g)',
    brandName: 'Omnigel',
    genericName: 'Diclofenac + Linseed Oil + Menthol',
    saltComposition: 'Diclofenac Diethylamine (1.16%) + Virgin Linseed Oil (3%) + Methyl Salicylate (10%) + Menthol (5%)',
    manufacturer: 'Cipla Health Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Omnigel fast-absorbing spray targets musculoskeletal pain, stiff neck, back pain, and sports sprains directly at the source.',
    uses: ['Back pain', 'Neck stiffness', 'Joint pain', 'Sports sprains'],
    sideEffects: ['Skin tingling sensation (normal)'],
    safetyAdvice: {
      pregnancy: 'Safe for topical use.',
      breastfeeding: 'Safe for topical use.',
      driving: 'No effect.',
      alcohol: 'Safe.',
    },
    mrp: 145.0,
    discountPrice: 125.0,
    discountPercentage: 14,
    rxRequired: false,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Can of 55g Spray',
    isPopular: true,
    inStock: true,
    stockCount: 340,
    rating: 4.7,
    reviewCount: 1980,
  },
  {
    id: 'med-cip-4',
    name: 'Ciplox 500 Tablet',
    brandName: 'Ciplox',
    genericName: 'Ciprofloxacin',
    saltComposition: 'Ciprofloxacin (500mg)',
    manufacturer: 'Cipla Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Ciplox 500 is a broad-spectrum antibiotic that treats various bacterial infections of the urinary tract, gastrointestinal tract, and chest.',
    uses: ['Bacterial infections', 'Urinary tract infection (UTI)', 'Typhoid fever'],
    sideEffects: ['Nausea', 'Mild diarrhea', 'Dizziness'],
    safetyAdvice: {
      pregnancy: 'Avoid during pregnancy.',
      breastfeeding: 'Consult doctor.',
      driving: 'May cause mild dizziness in some individuals.',
      alcohol: 'Avoid alcohol during antibiotic courses.',
    },
    mrp: 45.0,
    discountPrice: 38.0,
    discountPercentage: 15,
    rxRequired: true,
    category: 'Pain Relief',
    categorySlug: 'pain-relief',
    packForm: 'Strip of 10 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 220,
    rating: 4.6,
    reviewCount: 1400,
  },

  // --- 2. SUN PHARMA ---
  {
    id: 'med-sun-1',
    name: 'Pantocid 40 Tablet',
    brandName: 'Pantocid',
    genericName: 'Pantoprazole',
    saltComposition: 'Pantoprazole Sodium (40mg)',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Pantocid 40 is a proton pump inhibitor (PPI) that reduces acid production in the stomach, healing acid reflux, heartburn, and peptic ulcers.',
    uses: ['Gastroesophageal reflux disease (GERD)', 'Heartburn', 'Stomach ulcers', 'Acidity'],
    sideEffects: ['Headache', 'Mild abdominal pain (rare)'],
    safetyAdvice: {
      pregnancy: 'Consult doctor before taking.',
      breastfeeding: 'Safe in prescribed doses.',
      driving: 'No effect on motor abilities.',
      alcohol: 'Avoid alcohol as it worsens acid reflux.',
    },
    mrp: 165.0,
    discountPrice: 139.0,
    discountPercentage: 16,
    rxRequired: true,
    category: 'Stomach & Digestion',
    categorySlug: 'digestive',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 420,
    rating: 4.9,
    reviewCount: 4600,
  },
  {
    id: 'med-sun-2',
    name: 'Revital H Daily Health Supplement Capsules',
    brandName: 'Revital H',
    genericName: 'Ginseng + Multivitamins + Minerals',
    saltComposition: 'Ginseng Extract (42.5mg) + 10 Vitamins + 9 Minerals Complex',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=80',
    description: 'Revital H contains natural ginseng with a balanced formulation of essential vitamins and minerals to fight daily fatigue and boost stamina.',
    uses: ['Daily energy and stamina', 'Immunity support', 'Combat mental and physical fatigue'],
    sideEffects: ['None reported in recommended dosage'],
    safetyAdvice: {
      pregnancy: 'Safe for women in consultation with doctor.',
      breastfeeding: 'Safe.',
      driving: 'Enhances alertness.',
      alcohol: 'No known interaction.',
    },
    mrp: 330.0,
    discountPrice: 280.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Vitamins & Immunity',
    categorySlug: 'vitamins',
    packForm: 'Bottle of 30 softgels',
    isPopular: true,
    inStock: true,
    stockCount: 510,
    rating: 4.8,
    reviewCount: 3890,
  },
  {
    id: 'med-sun-3',
    name: 'Storvas 10 Tablet',
    brandName: 'Storvas',
    genericName: 'Atorvastatin',
    saltComposition: 'Atorvastatin (10mg)',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
    description: 'Storvas 10 belongs to the statin group of medicines, helping reduce LDL (bad cholesterol) and triglycerides while elevating HDL (good cholesterol).',
    uses: ['High cholesterol (Hyperlipidemia)', 'Prevention of heart attack and stroke'],
    sideEffects: ['Muscle ache (mild)', 'Nausea'],
    safetyAdvice: {
      pregnancy: 'Strictly prohibited during pregnancy.',
      breastfeeding: 'Not recommended.',
      driving: 'Safe.',
      alcohol: 'Avoid heavy alcohol intake.',
    },
    mrp: 110.0,
    discountPrice: 92.0,
    discountPercentage: 16,
    rxRequired: true,
    category: 'Heart & BP',
    categorySlug: 'heart-bp',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 310,
    rating: 4.8,
    reviewCount: 2150,
  },

  // --- 3. ABBOTT HEALTHCARE ---
  {
    id: 'med-abt-1',
    name: 'Thyronorm 100mcg Tablet',
    brandName: 'Thyronorm',
    genericName: 'Thyroxine Sodium',
    saltComposition: 'Thyroxine Sodium (100mcg)',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Thyronorm 100mcg is a synthetic thyroid hormone used in hormone replacement therapy for underactive thyroid glands (hypothyroidism).',
    uses: ['Hypothyroidism', 'Thyroid hormone replacement', 'Goitre prevention'],
    sideEffects: ['Palpitations (if overdosed)', 'Weight loss (if overdosed)'],
    safetyAdvice: {
      pregnancy: 'Essential to take during pregnancy under doctor guidance.',
      breastfeeding: 'Safe.',
      driving: 'No effect.',
      alcohol: 'No direct interaction.',
    },
    mrp: 185.0,
    discountPrice: 155.0,
    discountPercentage: 16,
    rxRequired: true,
    category: 'Vitamins & Immunity',
    categorySlug: 'vitamins',
    packForm: 'Bottle of 120 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 650,
    rating: 4.9,
    reviewCount: 6800,
  },
  {
    id: 'med-abt-2',
    name: 'Cremaffin Plus Mixed Fruit Syrup (225ml)',
    brandName: 'Cremaffin Plus',
    genericName: 'Liquid Paraffin + Milk of Magnesia + Sodium Picosulfate',
    saltComposition: 'Liquid Paraffin (3.75ml) + Milk of Magnesia (11.25ml) + Sodium Picosulfate (3.33mg)',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Cremaffin Plus is a gentle and effective laxative emulsion that provides overnight relief from constipation and softens stools.',
    uses: ['Chronic constipation', 'Piles relief', 'Painful bowel movements'],
    sideEffects: ['Mild abdominal cramps (rare)'],
    safetyAdvice: {
      pregnancy: 'Consult doctor before taking.',
      breastfeeding: 'Safe.',
      driving: 'No drowsiness.',
      alcohol: 'Stay hydrated with water.',
    },
    mrp: 295.0,
    discountPrice: 249.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Stomach & Digestion',
    categorySlug: 'digestive',
    packForm: 'Bottle of 225ml Syrup',
    isPopular: true,
    inStock: true,
    stockCount: 380,
    rating: 4.8,
    reviewCount: 3120,
  },
  {
    id: 'med-abt-3',
    name: 'Ensure Diabetes Care Powder (Vanilla 400g)',
    brandName: 'Ensure',
    genericName: 'Specialized Diabetes Nutritional Complex',
    saltComposition: 'Slow Release Complex Carbohydrates + Dual Fiber Blend + 32 Vital Nutrients',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Ensure Diabetes Care is a scientifically formulated nutritional supplement that helps manage blood glucose response while providing complete nutrition.',
    uses: ['Diabetes dietary support', 'Steady energy release', 'Weight management support'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'Safe under dietary supervision.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 750.0,
    discountPrice: 649.0,
    discountPercentage: 13,
    rxRequired: false,
    category: 'Diabetes Care',
    categorySlug: 'diabetes',
    packForm: 'Jar of 400g Powder',
    isPopular: true,
    inStock: true,
    stockCount: 220,
    rating: 4.9,
    reviewCount: 4250,
  },

  // --- 4. DR. REDDY'S LABORATORIES ---
  {
    id: 'med-drr-1',
    name: 'Omez 20mg Capsule',
    brandName: 'Omez',
    genericName: 'Omeprazole',
    saltComposition: 'Omeprazole (20mg)',
    manufacturer: "Dr. Reddy's Laboratories Ltd",
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Omez 20mg provides long-lasting relief from hyperacidity, acid reflux, stomach bloating, and indigestion by regulating gastric acid secretion.',
    uses: ['Acid reflux & GERD', 'Heartburn', 'Gastric ulcers', 'Zollinger-Ellison syndrome'],
    sideEffects: ['Nausea (rare)', 'Headache (mild)'],
    safetyAdvice: {
      pregnancy: 'Take only on medical advice.',
      breastfeeding: 'Safe in regular doses.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 65.0,
    discountPrice: 54.0,
    discountPercentage: 17,
    rxRequired: false,
    category: 'Stomach & Digestion',
    categorySlug: 'digestive',
    packForm: 'Strip of 20 capsules',
    isPopular: true,
    inStock: true,
    stockCount: 580,
    rating: 4.9,
    reviewCount: 5120,
  },
  {
    id: 'med-drr-2',
    name: 'Stamlo 5 Tablet',
    brandName: 'Stamlo',
    genericName: 'Amlodipine',
    saltComposition: 'Amlodipine Besylate (5mg)',
    manufacturer: "Dr. Reddy's Laboratories Ltd",
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Stamlo 5 is a calcium channel blocker that relaxes blood vessels, lowering blood pressure and improving coronary blood flow in angina.',
    uses: ['Hypertension (High Blood Pressure)', 'Chronic stable angina', 'Vasospastic angina'],
    sideEffects: ['Ankle swelling (mild)', 'Flushing'],
    safetyAdvice: {
      pregnancy: 'Consult cardiologist.',
      breastfeeding: 'Consult doctor.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol as it causes sharp drops in BP.',
    },
    mrp: 118.0,
    discountPrice: 99.0,
    discountPercentage: 16,
    rxRequired: true,
    category: 'Heart & BP',
    categorySlug: 'heart-bp',
    packForm: 'Strip of 15 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 390,
    rating: 4.8,
    reviewCount: 2900,
  },
  {
    id: 'med-drr-3',
    name: 'Econorm 250mg Probiotic Sachet',
    brandName: 'Econorm',
    genericName: 'Saccharomyces Boulardii',
    saltComposition: 'Lyophilized Saccharomyces boulardii (250mg)',
    manufacturer: "Dr. Reddy's Laboratories Ltd",
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=80',
    description: 'Econorm is a proven probiotic yeast supplement that restores healthy gut flora during antibiotic therapy and treats acute diarrhea.',
    uses: ['Antibiotic-associated diarrhea', 'Acute gastroenteritis', 'Gut microbiota imbalance'],
    sideEffects: ['None'],
    safetyAdvice: {
      pregnancy: 'Safe.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 52.0,
    discountPrice: 44.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Stomach & Digestion',
    categorySlug: 'digestive',
    packForm: 'Pack of 6 sachets (1g each)',
    isPopular: true,
    inStock: true,
    stockCount: 340,
    rating: 4.8,
    reviewCount: 1850,
  },

  // --- 5. HIMALAYA HERBAL & WELLNESS ---
  {
    id: 'med-him-1',
    name: 'Himalaya Liv.52 DS Tablets (Pack of 60)',
    brandName: 'Liv.52',
    genericName: 'Ayurvedic Hepatoprotective Formula',
    saltComposition: 'Himsra (Capparis spinosa 130mg) + Kasani (Cichorium intybus 130mg) + Mandur bhasma',
    manufacturer: 'The Himalaya Drug Company',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
    description: 'Himalaya Liv.52 DS is a double strength herbal formulation that protects the liver against toxins, enhances appetite, and supports healthy liver function.',
    uses: ['Liver detoxification', 'Loss of appetite', 'Fatty liver support', 'Alcoholic liver protection'],
    sideEffects: ['No known side effects, 100% ayurvedic'],
    safetyAdvice: {
      pregnancy: 'Safe to use.',
      breastfeeding: 'Safe to use.',
      driving: 'No effect.',
      alcohol: 'Supports liver health, but limiting alcohol is advised.',
    },
    mrp: 230.0,
    discountPrice: 195.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Ayurvedic & Herbal',
    categorySlug: 'ayurveda',
    packForm: 'Bottle of 60 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 620,
    rating: 4.9,
    reviewCount: 7800,
  },
  {
    id: 'med-him-2',
    name: 'Himalaya Cystone Tablets (Pack of 60)',
    brandName: 'Cystone',
    genericName: 'Ayurvedic Kidney Care Formula',
    saltComposition: 'Shilapushpa (Didymocarpus pedicellata 130mg) + Pasanabheda (Saxifraga ligulata 98mg)',
    manufacturer: 'The Himalaya Drug Company',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Himalaya Cystone naturally prevents and dissolves small kidney stones and crystals, while easing burning sensations during urination.',
    uses: ['Kidney stones (Calculi)', 'Urinary tract infection (UTI)', 'Burning micturition'],
    sideEffects: ['100% natural, no known side effects'],
    safetyAdvice: {
      pregnancy: 'Consult ayurvedic physician.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Drink abundant water.',
    },
    mrp: 195.0,
    discountPrice: 165.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Ayurvedic & Herbal',
    categorySlug: 'ayurveda',
    packForm: 'Bottle of 60 tablets',
    isPopular: true,
    inStock: true,
    stockCount: 490,
    rating: 4.8,
    reviewCount: 5400,
  },
  {
    id: 'med-him-3',
    name: 'Himalaya Purifying Neem Face Wash (150ml)',
    brandName: 'Himalaya Neem',
    genericName: 'Neem & Turmeric Face Wash',
    saltComposition: 'Neem (Azadirachta indica) + Turmeric (Curcuma longa)',
    manufacturer: 'The Himalaya Drug Company',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
    description: 'Himalaya Purifying Neem Face Wash is a soap-free, herbal formulation that clears impurities and helps clear pimples and acne.',
    uses: ['Acne and pimple prevention', 'Daily deep facial cleansing', 'Oil control'],
    sideEffects: ['Gentle on skin, dermatologically tested'],
    safetyAdvice: {
      pregnancy: 'Safe.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 210.0,
    discountPrice: 175.0,
    discountPercentage: 16,
    rxRequired: false,
    category: 'Skin Care',
    categorySlug: 'skin',
    packForm: 'Tube of 150ml',
    isPopular: true,
    inStock: true,
    stockCount: 550,
    rating: 4.8,
    reviewCount: 6200,
  },

  // --- 6. MANKIND PHARMA ---
  {
    id: 'med-man-1',
    name: 'Gas-O-Fast Sachet (Asli Jeera Instant Relief)',
    brandName: 'Gas-O-Fast',
    genericName: 'Ayurvedic Antacid Instant Effervescent',
    saltComposition: 'Svarjiksara (Shudh) 2.91g + Nimbukamlam (Shushk) 2.04g + Jeera Extract (50mg)',
    manufacturer: 'Mankind Pharma Ltd',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
    description: 'Gas-O-Fast delivers active ayurvedic antacid action within seconds to eliminate heavy gas, burning sensations, and acidity.',
    uses: ['Instant acidity relief', 'Gas and flatulence', 'Indigestion after meals'],
    sideEffects: ['None in moderation'],
    safetyAdvice: {
      pregnancy: 'Safe.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Provides quick relief after heavy meals or alcohol.',
    },
    mrp: 12.0,
    discountPrice: 10.0,
    discountPercentage: 16,
    rxRequired: false,
    category: 'Stomach & Digestion',
    categorySlug: 'digestive',
    packForm: 'Sachet of 5g Instant Effervescent',
    isPopular: true,
    inStock: true,
    stockCount: 890,
    rating: 4.9,
    reviewCount: 8200,
  },
  {
    id: 'med-man-2',
    name: 'Prega News One Step Pregnancy Test Card',
    brandName: 'Prega News',
    genericName: 'Urine hCG Pregnancy Diagnostic Card',
    saltComposition: 'Monoclonal anti-hCG antibodies test strip with rapid capillary action',
    manufacturer: 'Mankind Pharma Ltd',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
    description: 'Prega News provides 99% accurate pregnancy detection at home within 5 minutes using early morning urine drops.',
    uses: ['At-home pregnancy detection', 'Early hCG confirmation'],
    sideEffects: ['Diagnostic kit for external use only'],
    safetyAdvice: {
      pregnancy: 'Read instructions carefully on back of packet.',
      breastfeeding: 'N/A',
      driving: 'Safe.',
      alcohol: 'N/A',
    },
    mrp: 60.0,
    discountPrice: 48.0,
    discountPercentage: 20,
    rxRequired: false,
    category: 'Baby & Mother Care',
    categorySlug: 'baby',
    packForm: 'Single Test Card with Dropper',
    isPopular: true,
    inStock: true,
    stockCount: 750,
    rating: 4.9,
    reviewCount: 9400,
  },
  {
    id: 'med-man-3',
    name: 'Caldikind Plus Soft Gelatin Capsules',
    brandName: 'Caldikind Plus',
    genericName: 'Calcium + Calcitriol + Zinc + EPA + DHA',
    saltComposition: 'Calcium Carbonate (500mg) + Calcitriol (0.25mcg) + Zinc Sulphate (7.5mg) + Omega 3 Fatty Acids',
    manufacturer: 'Mankind Pharma Ltd',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=80',
    description: 'Caldikind Plus provides maximum calcium absorption with active calcitriol and omega-3 to reinforce bone mineral density and joint flexibility.',
    uses: ['Osteoporosis prevention', 'Post-menopausal bone health', 'Calcium deficiency', 'Joint strength'],
    sideEffects: ['None in prescribed intake'],
    safetyAdvice: {
      pregnancy: 'Highly recommended for prenatal bone support.',
      breastfeeding: 'Safe.',
      driving: 'Safe.',
      alcohol: 'Safe.',
    },
    mrp: 140.0,
    discountPrice: 118.0,
    discountPercentage: 15,
    rxRequired: false,
    category: 'Vitamins & Immunity',
    categorySlug: 'vitamins',
    packForm: 'Strip of 10 softgels',
    isPopular: true,
    inStock: true,
    stockCount: 410,
    rating: 4.8,
    reviewCount: 3100,
  },
  {
    id: 'med-man-4',
    name: 'Unwanted-72 Emergency Contraceptive Tablet',
    brandName: 'Unwanted-72',
    genericName: 'Levonorgestrel',
    saltComposition: 'Levonorgestrel (1.5mg)',
    manufacturer: 'Mankind Pharma Ltd',
    image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=500&auto=format&fit=crop&q=80',
    description: 'Unwanted-72 is an emergency oral contraceptive pill that prevents unplanned pregnancy when taken within 72 hours of unprotected intercourse.',
    uses: ['Emergency contraception within 72 hours'],
    sideEffects: ['Nausea', 'Delayed or early menstrual cycle (temporary)'],
    safetyAdvice: {
      pregnancy: 'Do not use if already pregnant.',
      breastfeeding: 'Consult doctor.',
      driving: 'Safe.',
      alcohol: 'Avoid alcohol.',
    },
    mrp: 110.0,
    discountPrice: 92.0,
    discountPercentage: 16,
    rxRequired: false,
    category: 'Sexual Wellness',
    categorySlug: 'wellness',
    packForm: 'Single Tablet Pack',
    isPopular: true,
    inStock: true,
    stockCount: 680,
    rating: 4.9,
    reviewCount: 7100,
  },
];

export const MOCK_PHARMACIES: Pharmacy[] = [
  {
    id: 'pharm-1',
    name: 'Sharma Medical & Surgical Store',
    logo: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=200&auto=format&fit=crop&q=80',
    licenseNumber: 'DL-PB-2023-984210',
    rating: 4.8,
    reviewCount: 1420,
    distanceKm: 0.8,
    estimatedDeliveryTimeMinutes: 12,
    isOpenNow: true,
    openingTime: '07:30 AM',
    closingTime: '11:00 PM',
    isVerified: true,
    phone: '+91 98765 11223',
    deliveryFee: 0,
    freeDeliveryAbove: 199,
    address: {
      line1: 'Shop No. 14, Main Market, Homeland City',
      city: 'Karimpur',
      pincode: '144522',
      latitude: 31.1471,
      longitude: 75.3412,
    },
  },
  {
    id: 'pharm-2',
    name: 'Apollo Pharmacy 24x7',
    logo: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=200&auto=format&fit=crop&q=80',
    licenseNumber: 'DL-PB-2022-874512',
    rating: 4.7,
    reviewCount: 2890,
    distanceKm: 1.4,
    estimatedDeliveryTimeMinutes: 15,
    isOpenNow: true,
    openingTime: '12:00 AM',
    closingTime: '11:59 PM',
    isVerified: true,
    phone: '+91 98765 22334',
    deliveryFee: 15,
    freeDeliveryAbove: 299,
    address: {
      line1: 'SCO 21-22, Phase 5 Commercial Complex',
      city: 'Karimpur',
      pincode: '144522',
      latitude: 31.1512,
      longitude: 75.3489,
    },
  },
  {
    id: 'pharm-3',
    name: 'MedPlus Chemists & Druggists',
    logo: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=200&auto=format&fit=crop&q=80',
    licenseNumber: 'DL-PB-2021-654987',
    rating: 4.6,
    reviewCount: 980,
    distanceKm: 2.1,
    estimatedDeliveryTimeMinutes: 18,
    isOpenNow: true,
    openingTime: '08:00 AM',
    closingTime: '10:30 PM',
    isVerified: true,
    phone: '+91 98765 33445',
    deliveryFee: 20,
    freeDeliveryAbove: 250,
    address: {
      line1: 'Near Civil Hospital Road',
      city: 'Karimpur',
      pincode: '144522',
      latitude: 31.1398,
      longitude: 75.3354,
    },
  },
];

export const MOCK_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    label: 'Home',
    recipientName: 'Gurpreet Singh',
    phone: '+91 98765 43210',
    houseFlatNumber: 'House #121',
    apartmentBuilding: 'Homeland City Phase 5',
    streetAddress: 'Near Community Park, Main Boulevard',
    landmark: 'Opposite Golden Plaza',
    city: 'Karimpur',
    pincode: '144522',
    isDefault: true,
  },
  {
    id: 'addr-2',
    label: 'Work',
    recipientName: 'Gurpreet Singh',
    phone: '+91 98765 43210',
    houseFlatNumber: 'Cabin #4B',
    apartmentBuilding: 'IT Park Tower A',
    streetAddress: 'Sector 62, Industrial Area',
    landmark: 'Near Metro Station Gate 2',
    city: 'Mohali',
    pincode: '160062',
    isDefault: false,
  },
];

export const MOCK_SAVED_ADDRESSES = MOCK_ADDRESSES;

export const MOCK_USER: User = {
  id: 'user-1',
  phoneNumber: '+91 98765 43210',
  name: 'Gurpreet Singh',
  email: 'gurpreet.singh@example.com',
  savedAddresses: MOCK_ADDRESSES,
  defaultAddressId: 'addr-1',
  createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
};

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Order Delivered Successfully 🎉',
    message: 'Your order from Sharma Medical Store containing Dolo 650 & Becosules Z was delivered on time.',
    timestamp: Date.now() - 1000 * 60 * 30,
    type: 'order_status',
    isRead: false,
    orderId: 'ord-101',
  },
  {
    id: 'notif-2',
    title: 'Flat 15% OFF on Chronic Care',
    message: 'Apollo Pharmacy is offering 15% OFF on all diabetes and heart care medications today.',
    timestamp: Date.now() - 1000 * 60 * 60 * 4,
    type: 'offer_received',
    isRead: false,
  },
];
