import { Order, OrderStatus, OrderTimelineEvent } from '../types/order';
import { PharmacyOffer } from '../types/offer';
import { Address } from '../types/user';
import { Prescription } from '../types/prescription';
import { apiClient } from './apiClient';
import { ENV } from '../config/env';

export class OrderService {
  private static orders: Order[] | null = null;

  private static getInitialOrders(): Order[] {
    if (this.orders) return this.orders;

    this.orders = [
      {
        id: 'ord-101',
        orderNumber: 'DW-8924',
        createdAt: Date.now() - 45 * 60 * 1000,
        status: 'out_for_delivery',
        statusText: 'Out for Delivery',
        statusDescription: 'Your rider Ramesh is on the way to deliver your order.',
        items: [
          {
            medicineId: 'med-1',
            medicineName: 'Dolo 650 Tablet',
            genericName: 'Paracetamol',
            packForm: 'Strip of 15 Tablets',
            unitPrice: 28.5,
            quantity: 2,
            totalPrice: 57.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80',
          },
          {
            medicineId: 'med-2',
            medicineName: 'Augmentin 625 Duo Tablet',
            genericName: 'Amoxycillin and Potassium Clavulanate',
            packForm: 'Strip of 10 Tablets',
            unitPrice: 189.0,
            quantity: 1,
            totalPrice: 189.0,
            rxRequired: true,
            image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 2,
        selectedPharmacy: {
          id: 'pharm-apollo',
          name: 'Apollo Pharmacy 24x7',
          logo: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2022-874512',
          rating: 4.9,
          reviewCount: 2890,
          distanceKm: 0.8,
          estimatedDeliveryTimeMinutes: 10,
          isOpenNow: true,
          openingTime: '12:00 AM',
          closingTime: '11:59 PM',
          isVerified: true,
          phone: '+91 98765 22334',
          deliveryFee: 0,
          freeDeliveryAbove: 199,
          address: {
            line1: 'SCO 21-22, Phase 5 Commercial Complex',
            city: 'Karimpur',
            pincode: '144522',
            latitude: 31.1512,
            longitude: 75.3489,
          },
        },
        hasRxItems: true,
        itemSubtotal: 246.0,
        mrpTotal: 291.5,
        discount: 45.5,
        deliveryFee: 0,
        taxes: 4.0,
        totalAmount: 250.0,
        savingsTotal: 45.5,
        deliveryAddress: {
          id: 'addr-1',
          label: 'Home',
          recipientName: 'Aryan Kumar',
          phone: '+91 98765 43210',
          houseFlatNumber: 'House No. 412',
          apartmentBuilding: 'Block B',
          streetAddress: 'Green Avenue, Sector 4',
          city: 'Karimpur',
          pincode: '144522',
          isDefault: true,
        },
        deliveryInstructions: 'Ring bell and leave at door',
        estimatedDeliveryTimestamp: Date.now() + 15 * 60 * 1000,
        rider: {
          name: 'Ramesh Kumar',
          phone: '+91 98451 22334',
          vehicleNumber: 'KA 03 HM 4812',
          rating: 4.9,
        },
        timeline: [
          {
            id: 't-1',
            status: 'request_created',
            title: 'Order Request Created',
            description: 'Medicine cart submitted for pharmacy matching',
            timestamp: Date.now() - 45 * 60 * 1000,
            isCompleted: true,
            isCurrent: false,
          },
          {
            id: 't-2',
            status: 'offers_received',
            title: 'Offers Received',
            description: '4 local verified pharmacies sent competitive quotes',
            timestamp: Date.now() - 40 * 60 * 1000,
            isCompleted: true,
            isCurrent: false,
          },
          {
            id: 't-3',
            status: 'offer_selected',
            title: 'Offer Accepted',
            description: 'Selected Apollo Pharmacy (Best Price & Fastest Delivery)',
            timestamp: Date.now() - 35 * 60 * 1000,
            isCompleted: true,
            isCurrent: false,
          },
          {
            id: 't-4',
            status: 'preparing',
            title: 'Prescription Verified & Medicines Packed',
            description: 'Pharmacist verified prescription and sealed tamper-proof bag',
            timestamp: Date.now() - 25 * 60 * 1000,
            isCompleted: true,
            isCurrent: false,
          },
          {
            id: 't-5',
            status: 'out_for_delivery',
            title: 'Out for Delivery',
            description: 'Rider Ramesh Kumar is on the way (KA 03 HM 4812)',
            timestamp: Date.now() - 10 * 60 * 1000,
            isCompleted: false,
            isCurrent: true,
          },
          {
            id: 't-6',
            status: 'delivered',
            title: 'Delivered',
            description: 'Order delivered to doorstep',
            timestamp: 0,
            isCompleted: false,
            isCurrent: false,
          },
        ],
      },
      {
        id: 'ord-102',
        orderNumber: 'DW-8210',
        createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 16 Aug 2026, 04:35 PM',
        items: [
          {
            medicineId: 'med-3',
            medicineName: 'Pan 40 Tablet',
            genericName: 'Pantoprazole',
            packForm: 'Strip of 15 Tablets',
            unitPrice: 165.0,
            quantity: 1,
            totalPrice: 165.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 1,
        selectedPharmacy: {
          id: 'pharm-medplus',
          name: 'MedPlus Chemists & Druggists',
          logo: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-654321',
          rating: 4.8,
          reviewCount: 1980,
          distanceKm: 1.2,
          estimatedDeliveryTimeMinutes: 12,
          isOpenNow: true,
          openingTime: '08:00 AM',
          closingTime: '11:00 PM',
          isVerified: true,
          phone: '+91 98765 33445',
          deliveryFee: 0,
          freeDeliveryAbove: 249,
          address: {
            line1: 'SCF 8-9, Sector 2 Market',
            city: 'Karimpur',
            pincode: '144522',
            latitude: 31.1445,
            longitude: 75.3398,
          },
        },
        hasRxItems: false,
        itemSubtotal: 165.0,
        mrpTotal: 195.0,
        discount: 30.0,
        deliveryFee: 0,
        taxes: 0,
        totalAmount: 165.0,
        savingsTotal: 30.0,
        deliveryAddress: {
          id: 'addr-1',
          label: 'Home',
          recipientName: 'Aryan Kumar',
          phone: '+91 98765 43210',
          houseFlatNumber: 'House No. 412',
          apartmentBuilding: 'Block B',
          streetAddress: 'Green Avenue, Sector 4',
          city: 'Karimpur',
          pincode: '144522',
          isDefault: true,
        },
        estimatedDeliveryTimestamp: Date.now() - 2 * 24 * 60 * 60 * 1000 + 35 * 60 * 1000,
        timeline: [
          {
            id: 't-201',
            status: 'request_created',
            title: 'Order Placed',
            description: 'Requirement sent to pharmacies',
            timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
            isCompleted: true,
            isCurrent: false,
          },
          {
            id: 't-202',
            status: 'delivered',
            title: 'Delivered',
            description: 'Delivered by MedPlus rider',
            timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000 + 32 * 60 * 1000,
            isCompleted: true,
            isCurrent: true,
          },
        ],
      },
      {
        id: 'ord-103',
        orderNumber: 'DW-4819',
        createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 15 Aug 2026, 11:20 AM',
        items: [
          {
            medicineId: 'med-5',
            medicineName: 'Shelcal 500 Tablet',
            genericName: 'Calcium + Vitamin D3',
            packForm: 'Strip of 15 Tablets',
            unitPrice: 119.5,
            quantity: 2,
            totalPrice: 239.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 2,
        selectedPharmacy: {
          id: 'pharm-guardian',
          name: 'Guardian Lifecare Pharmacy',
          logo: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-729103',
          rating: 4.7,
          reviewCount: 1420,
          distanceKm: 2.1,
          estimatedDeliveryTimeMinutes: 18,
          isOpenNow: true,
          openingTime: '09:00 AM',
          closingTime: '10:00 PM',
          isVerified: true,
          phone: '+91 98765 44556',
          deliveryFee: 15,
          freeDeliveryAbove: 299,
          address: {
            line1: 'Shop No. 12, Main VIP Road',
            city: 'Karimpur',
            pincode: '144522',
            latitude: 31.1567,
            longitude: 75.3524,
          },
        },
        hasRxItems: false,
        itemSubtotal: 239.0,
        mrpTotal: 270.0,
        discount: 31.0,
        deliveryFee: 15,
        taxes: 2.0,
        totalAmount: 256.0,
        savingsTotal: 31.0,
        deliveryAddress: {
          id: 'addr-1',
          label: 'Home',
          recipientName: 'Aryan Kumar',
          phone: '+91 98765 43210',
          houseFlatNumber: 'House No. 412',
          apartmentBuilding: 'Block B',
          streetAddress: 'Green Avenue, Sector 4',
          city: 'Karimpur',
          pincode: '144522',
          isDefault: true,
        },
        estimatedDeliveryTimestamp: Date.now() - 3 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000,
        timeline: [
          {
            id: 't-301',
            status: 'request_created',
            title: 'Order Placed',
            description: 'Order placed by user',
            timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
            isCompleted: true,
            isCurrent: false,
          },
          {
            id: 't-302',
            status: 'delivered',
            title: 'Delivered',
            description: 'Delivered by Guardian rider',
            timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000 + 38 * 60 * 1000,
            isCompleted: true,
            isCurrent: true,
          },
        ],
      },
      {
        id: 'ord-104',
        orderNumber: 'DW-1029',
        createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 13 Aug 2026, 02:15 PM',
        items: [
          {
            medicineId: 'med-1',
            medicineName: 'Crocin 650 Advance',
            genericName: 'Paracetamol',
            packForm: 'Strip of 15 Tablets',
            unitPrice: 35.0,
            quantity: 3,
            totalPrice: 105.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 3,
        selectedPharmacy: {
          id: 'pharm-apollo',
          name: 'Apollo Pharmacy 24x7',
          logo: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2022-874512',
          rating: 4.9,
          reviewCount: 2890,
          distanceKm: 0.8,
          estimatedDeliveryTimeMinutes: 10,
          isOpenNow: true,
          openingTime: '12:00 AM',
          closingTime: '11:59 PM',
          isVerified: true,
          phone: '+91 98765 22334',
          deliveryFee: 0,
          freeDeliveryAbove: 199,
          address: {
            line1: 'SCO 21-22, Phase 5 Commercial Complex',
            city: 'Karimpur',
            pincode: '144522',
            latitude: 31.1512,
            longitude: 75.3489,
          },
        },
        hasRxItems: false,
        itemSubtotal: 105.0,
        mrpTotal: 120.0,
        discount: 15.0,
        deliveryFee: 0,
        taxes: 1.0,
        totalAmount: 106.0,
        savingsTotal: 15.0,
        deliveryAddress: {
          id: 'addr-1',
          label: 'Home',
          recipientName: 'Aryan Kumar',
          phone: '+91 98765 43210',
          houseFlatNumber: 'House No. 412',
          apartmentBuilding: 'Block B',
          streetAddress: 'Green Avenue, Sector 4',
          city: 'Karimpur',
          pincode: '144522',
          isDefault: true,
        },
        estimatedDeliveryTimestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000,
        timeline: [
          { id: 't-401', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-402', status: 'delivered', title: 'Delivered', description: 'Delivered by Apollo rider', timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-105',
        orderNumber: 'DW-9912',
        createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 11 Aug 2026, 09:12 AM',
        items: [
          {
            medicineId: 'med-6',
            medicineName: 'Combiflam Tablet',
            genericName: 'Ibuprofen + Paracetamol',
            packForm: 'Strip of 20 Tablets',
            unitPrice: 42.0,
            quantity: 1,
            totalPrice: 42.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 1,
        selectedPharmacy: {
          id: 'pharm-medplus',
          name: 'MedPlus Chemists & Druggists',
          logo: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-654321',
          rating: 4.8,
          reviewCount: 1980,
          distanceKm: 1.2,
          isVerified: true,
          phone: '+91 98765 33445',
          deliveryFee: 0,
          freeDeliveryAbove: 249,
          estimatedDeliveryTimeMinutes: 12,
          isOpenNow: true,
          openingTime: '08:00 AM',
          closingTime: '11:00 PM',
          address: { line1: 'SCF 8-9, Sector 2 Market', city: 'Karimpur', pincode: '144522', latitude: 31.1445, longitude: 75.3398 },
        },
        hasRxItems: false,
        itemSubtotal: 42.0,
        mrpTotal: 50.0,
        discount: 8.0,
        deliveryFee: 15,
        taxes: 1.0,
        totalAmount: 58.0,
        savingsTotal: 8.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 7 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000,
        timeline: [
          { id: 't-501', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-502', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000 + 22 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-106',
        orderNumber: 'DW-8321',
        createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 08 Aug 2026, 06:40 PM',
        items: [
          {
            medicineId: 'med-7',
            medicineName: 'Becosules Capsules',
            genericName: 'Vitamin B-Complex',
            packForm: 'Strip of 20 Capsules',
            unitPrice: 52.0,
            quantity: 2,
            totalPrice: 104.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 2,
        selectedPharmacy: {
          id: 'pharm-guardian',
          name: 'Guardian Lifecare Pharmacy',
          logo: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-729103',
          rating: 4.7,
          reviewCount: 1420,
          distanceKm: 2.1,
          isVerified: true,
          phone: '+91 98765 44556',
          deliveryFee: 15,
          freeDeliveryAbove: 299,
          estimatedDeliveryTimeMinutes: 18,
          isOpenNow: true,
          openingTime: '09:00 AM',
          closingTime: '10:00 PM',
          address: { line1: 'Shop No. 12, Main VIP Road', city: 'Karimpur', pincode: '144522', latitude: 31.1567, longitude: 75.3524 },
        },
        hasRxItems: false,
        itemSubtotal: 104.0,
        mrpTotal: 120.0,
        discount: 16.0,
        deliveryFee: 0,
        taxes: 2.0,
        totalAmount: 106.0,
        savingsTotal: 16.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 10 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000,
        timeline: [
          { id: 't-601', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-602', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000 + 38 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-107',
        orderNumber: 'DW-2234',
        createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 06 Aug 2026, 12:35 PM',
        items: [
          {
            medicineId: 'med-8',
            medicineName: 'Allegra 120mg Tablet',
            genericName: 'Fexofenadine Hydrochloride',
            packForm: 'Strip of 10 Tablets',
            unitPrice: 218.0,
            quantity: 1,
            totalPrice: 218.0,
            rxRequired: true,
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 1,
        selectedPharmacy: {
          id: 'pharm-apollo',
          name: 'Apollo Pharmacy 24x7',
          logo: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2022-874512',
          rating: 4.9,
          reviewCount: 2890,
          distanceKm: 0.8,
          isVerified: true,
          phone: '+91 98765 22334',
          deliveryFee: 0,
          freeDeliveryAbove: 199,
          estimatedDeliveryTimeMinutes: 10,
          isOpenNow: true,
          openingTime: '12:00 AM',
          closingTime: '11:59 PM',
          address: { line1: 'SCO 21-22, Phase 5 Commercial Complex', city: 'Karimpur', pincode: '144522', latitude: 31.1512, longitude: 75.3489 },
        },
        hasRxItems: true,
        itemSubtotal: 218.0,
        mrpTotal: 250.0,
        discount: 32.0,
        deliveryFee: 0,
        taxes: 3.0,
        totalAmount: 221.0,
        savingsTotal: 32.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 12 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000,
        timeline: [
          { id: 't-701', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 12 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-702', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 12 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-108',
        orderNumber: 'DW-7182',
        createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 03 Aug 2026, 03:50 PM',
        items: [
          {
            medicineId: 'med-9',
            medicineName: 'Zifi 200 Tablet',
            genericName: 'Cefixime',
            packForm: 'Strip of 10 Tablets',
            unitPrice: 104.5,
            quantity: 2,
            totalPrice: 209.0,
            rxRequired: true,
            image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 2,
        selectedPharmacy: {
          id: 'pharm-medplus',
          name: 'MedPlus Chemists & Druggists',
          logo: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-654321',
          rating: 4.8,
          reviewCount: 1980,
          distanceKm: 1.2,
          isVerified: true,
          phone: '+91 98765 33445',
          deliveryFee: 0,
          freeDeliveryAbove: 249,
          estimatedDeliveryTimeMinutes: 12,
          isOpenNow: true,
          openingTime: '08:00 AM',
          closingTime: '11:00 PM',
          address: { line1: 'SCF 8-9, Sector 2 Market', city: 'Karimpur', pincode: '144522', latitude: 31.1445, longitude: 75.3398 },
        },
        hasRxItems: true,
        itemSubtotal: 209.0,
        mrpTotal: 240.0,
        discount: 31.0,
        deliveryFee: 0,
        taxes: 2.0,
        totalAmount: 211.0,
        savingsTotal: 31.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 15 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000,
        timeline: [
          { id: 't-801', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 15 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-802', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 15 * 24 * 60 * 60 * 1000 + 35 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-109',
        orderNumber: 'DW-3948',
        createdAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 31 Jul 2026, 05:10 PM',
        items: [
          {
            medicineId: 'med-10',
            medicineName: 'Volini Pain Relief Gel',
            genericName: 'Diclofenac Diethylamine',
            packForm: 'Tube of 50g',
            unitPrice: 145.0,
            quantity: 1,
            totalPrice: 145.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1550572017-edb79a557451?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 1,
        selectedPharmacy: {
          id: 'pharm-guardian',
          name: 'Guardian Lifecare Pharmacy',
          logo: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-729103',
          rating: 4.7,
          reviewCount: 1420,
          distanceKm: 2.1,
          isVerified: true,
          phone: '+91 98765 44556',
          deliveryFee: 15,
          freeDeliveryAbove: 299,
          estimatedDeliveryTimeMinutes: 18,
          isOpenNow: true,
          openingTime: '09:00 AM',
          closingTime: '10:00 PM',
          address: { line1: 'Shop No. 12, Main VIP Road', city: 'Karimpur', pincode: '144522', latitude: 31.1567, longitude: 75.3524 },
        },
        hasRxItems: false,
        itemSubtotal: 145.0,
        mrpTotal: 170.0,
        discount: 25.0,
        deliveryFee: 15,
        taxes: 1.0,
        totalAmount: 161.0,
        savingsTotal: 25.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 18 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000,
        timeline: [
          { id: 't-901', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 18 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-902', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 18 * 24 * 60 * 60 * 1000 + 36 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-110',
        orderNumber: 'DW-1083',
        createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 29 Jul 2026, 10:20 AM',
        items: [
          {
            medicineId: 'med-11',
            medicineName: 'Otrivin Oxy Fast Relief',
            genericName: 'Xylometazoline Hydrochloride',
            packForm: 'Bottle of 10ml Nasal Spray',
            unitPrice: 98.0,
            quantity: 1,
            totalPrice: 98.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 1,
        selectedPharmacy: {
          id: 'pharm-apollo',
          name: 'Apollo Pharmacy 24x7',
          logo: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2022-874512',
          rating: 4.9,
          reviewCount: 2890,
          distanceKm: 0.8,
          isVerified: true,
          phone: '+91 98765 22334',
          deliveryFee: 0,
          freeDeliveryAbove: 199,
          estimatedDeliveryTimeMinutes: 10,
          isOpenNow: true,
          openingTime: '12:00 AM',
          closingTime: '11:59 PM',
          address: { line1: 'SCO 21-22, Phase 5 Commercial Complex', city: 'Karimpur', pincode: '144522', latitude: 31.1512, longitude: 75.3489 },
        },
        hasRxItems: false,
        itemSubtotal: 98.0,
        mrpTotal: 110.0,
        discount: 12.0,
        deliveryFee: 15,
        taxes: 1.0,
        totalAmount: 114.0,
        savingsTotal: 12.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 20 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000,
        timeline: [
          { id: 't-1001', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 20 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-1002', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 20 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-111',
        orderNumber: 'DW-5491',
        createdAt: Date.now() - 25 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 24 Jul 2026, 11:30 AM',
        items: [
          {
            medicineId: 'med-12',
            medicineName: 'Evion 400mg Capsule',
            genericName: 'Tocopheryl Acetate (Vitamin E)',
            packForm: 'Strip of 10 Capsules',
            unitPrice: 35.5,
            quantity: 3,
            totalPrice: 106.5,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 3,
        selectedPharmacy: {
          id: 'pharm-medplus',
          name: 'MedPlus Chemists & Druggists',
          logo: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-654321',
          rating: 4.8,
          reviewCount: 1980,
          distanceKm: 1.2,
          isVerified: true,
          phone: '+91 98765 33445',
          deliveryFee: 0,
          freeDeliveryAbove: 249,
          estimatedDeliveryTimeMinutes: 12,
          isOpenNow: true,
          openingTime: '08:00 AM',
          closingTime: '11:00 PM',
          address: { line1: 'SCF 8-9, Sector 2 Market', city: 'Karimpur', pincode: '144522', latitude: 31.1445, longitude: 75.3398 },
        },
        hasRxItems: false,
        itemSubtotal: 106.5,
        mrpTotal: 120.0,
        discount: 13.5,
        deliveryFee: 15,
        taxes: 1.0,
        totalAmount: 122.5,
        savingsTotal: 13.5,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 25 * 24 * 60 * 60 * 1000 + 35 * 60 * 1000,
        timeline: [
          { id: 't-1101', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 25 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-1102', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 25 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-112',
        orderNumber: 'DW-6382',
        createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 19 Jul 2026, 04:20 PM',
        items: [
          {
            medicineId: 'med-13',
            medicineName: 'Saridon Headache Tablet',
            genericName: 'Propyphenazone + Paracetamol + Caffeine',
            packForm: 'Strip of 10 Tablets',
            unitPrice: 40.0,
            quantity: 2,
            totalPrice: 80.0,
            rxRequired: false,
            image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 2,
        selectedPharmacy: {
          id: 'pharm-guardian',
          name: 'Guardian Lifecare Pharmacy',
          logo: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-729103',
          rating: 4.7,
          reviewCount: 1420,
          distanceKm: 2.1,
          isVerified: true,
          phone: '+91 98765 44556',
          deliveryFee: 15,
          freeDeliveryAbove: 299,
          estimatedDeliveryTimeMinutes: 18,
          isOpenNow: true,
          openingTime: '09:00 AM',
          closingTime: '10:00 PM',
          address: { line1: 'Shop No. 12, Main VIP Road', city: 'Karimpur', pincode: '144522', latitude: 31.1567, longitude: 75.3524 },
        },
        hasRxItems: false,
        itemSubtotal: 80.0,
        mrpTotal: 96.0,
        discount: 16.0,
        deliveryFee: 15,
        taxes: 1.0,
        totalAmount: 96.0,
        savingsTotal: 16.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 30 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000,
        timeline: [
          { id: 't-1201', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 30 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-1202', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 30 * 24 * 60 * 60 * 1000 + 35 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
      {
        id: 'ord-113',
        orderNumber: 'DW-2910',
        createdAt: Date.now() - 35 * 24 * 60 * 60 * 1000,
        status: 'delivered',
        statusText: 'Delivered',
        statusDescription: 'Order delivered on 14 Jul 2026, 01:10 PM',
        items: [
          {
            medicineId: 'med-2',
            medicineName: 'Augmentin 625 Duo Tablet',
            genericName: 'Amoxycillin and Potassium Clavulanate',
            packForm: 'Strip of 10 Tablets',
            unitPrice: 189.0,
            quantity: 1,
            totalPrice: 189.0,
            rxRequired: true,
            image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&auto=format&fit=crop&q=80',
          },
        ],
        itemCount: 1,
        selectedPharmacy: {
          id: 'pharm-medplus',
          name: 'MedPlus Chemists & Druggists',
          logo: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=200&auto=format&fit=crop&q=80',
          licenseNumber: 'DL-PB-2021-654321',
          rating: 4.8,
          reviewCount: 1980,
          distanceKm: 1.2,
          isVerified: true,
          phone: '+91 98765 33445',
          deliveryFee: 0,
          freeDeliveryAbove: 249,
          estimatedDeliveryTimeMinutes: 12,
          isOpenNow: true,
          openingTime: '08:00 AM',
          closingTime: '11:00 PM',
          address: { line1: 'SCF 8-9, Sector 2 Market', city: 'Karimpur', pincode: '144522', latitude: 31.1445, longitude: 75.3398 },
        },
        hasRxItems: true,
        itemSubtotal: 189.0,
        mrpTotal: 220.0,
        discount: 31.0,
        deliveryFee: 0,
        taxes: 2.0,
        totalAmount: 191.0,
        savingsTotal: 31.0,
        deliveryAddress: { id: 'addr-1', label: 'Home', recipientName: 'Aryan Kumar', phone: '+91 98765 43210', houseFlatNumber: 'House No. 412', apartmentBuilding: 'Block B', streetAddress: 'Green Avenue, Sector 4', city: 'Karimpur', pincode: '144522', isDefault: true },
        estimatedDeliveryTimestamp: Date.now() - 35 * 24 * 60 * 60 * 1000 + 40 * 60 * 1000,
        timeline: [
          { id: 't-1301', status: 'request_created', title: 'Placed', description: 'Order placed by user', timestamp: Date.now() - 35 * 24 * 60 * 60 * 1000, isCompleted: true, isCurrent: false },
          { id: 't-1302', status: 'delivered', title: 'Delivered', description: 'Delivered successfully by rider', timestamp: Date.now() - 35 * 24 * 60 * 60 * 1000 + 35 * 60 * 1000, isCompleted: true, isCurrent: true },
        ],
      },
    ];

    return this.orders || [];
  }

  static async getOrders(statusFilter?: 'active' | 'completed' | 'cancelled'): Promise<Order[]> {
    try {
      const response = await apiClient.get<Order[]>('/orders', statusFilter ? { status: statusFilter } : undefined);
      if (response.success && Array.isArray(response.data)) {
        return response.data;
      }
    } catch {
      // fallback
    }

    if (ENV.ENABLE_MOCK_FALLBACK) {
      await this.delay(100);
      const all = this.getInitialOrders();
      if (!statusFilter) return [...all];

      if (statusFilter === 'active') {
        return all.filter((o) =>
          ['request_created', 'finding_pharmacy', 'offers_received', 'offer_selected', 'preparing', 'packed', 'out_for_delivery'].includes(
            o.status
          )
        );
      }
      if (statusFilter === 'completed') {
        return all.filter((o) => o.status === 'delivered');
      }
      if (statusFilter === 'cancelled') {
        return all.filter((o) => o.status === 'cancelled');
      }
    }
    return [];
  }

  static async getOrderById(orderId: string): Promise<Order | null> {
    try {
      const response = await apiClient.get<Order>(`/orders/${orderId}`);
      if (response.success && response.data) {
        return response.data;
      }
    } catch {
      // fallback
    }

    if (ENV.ENABLE_MOCK_FALLBACK) {
      await this.delay(100);
      const all = this.getInitialOrders();
      const order = all.find((o) => o.id === orderId);
      return order || all[0] || null;
    }
    return null;
  }

  static async createOrderFromOffer(
    offer: PharmacyOffer,
    address: Address,
    prescription?: Prescription,
    deliveryInstructions?: string
  ): Promise<Order> {
    try {
      const response = await apiClient.post<Order>('/orders', {
        offerId: offer.id,
        cartId: offer.cartId,
        pharmacyId: offer.pharmacyId,
        addressId: address.id,
        prescriptionId: prescription?.id,
        deliveryInstructions,
      });
      if (response.success && response.data) {
        return response.data;
      }
    } catch {
      // fallback
    }

    const all = this.getInitialOrders();
    const newOrder: Order = {
      id: `ord-${Date.now()}`,
      orderNumber: `DW-${Math.floor(1000 + Math.random() * 9000)}`,
      createdAt: Date.now(),
      status: 'offer_selected',
      statusText: 'Order Placed',
      statusDescription: 'Your order is being sent to the pharmacy for verification.',
      items: offer.itemPrices.map((item) => ({
        medicineId: item.medicineId,
        medicineName: item.medicineName,
        packForm: 'Strip / Bottle',
        unitPrice: item.unitPrice,
        quantity: item.quantity,
        totalPrice: item.totalPrice,
        rxRequired: false,
      })),
      itemCount: offer.itemPrices.reduce((sum, item) => sum + item.quantity, 0),
      selectedPharmacy: offer.pharmacy,
      selectedOffer: offer,
      prescription,
      hasRxItems: !!prescription,
      itemSubtotal: offer.medicineSubtotal,
      mrpTotal: offer.mrpTotal,
      discount: offer.discountAmount,
      deliveryFee: offer.deliveryFee,
      taxes: offer.taxesAndFees,
      totalAmount: offer.finalPayableAmount,
      savingsTotal: offer.totalSavings,
      deliveryAddress: address,
      deliveryInstructions,
      estimatedDeliveryTimestamp: Date.now() + offer.estimatedDeliveryMinutes * 60 * 1000,
      timeline: [
        {
          id: `t-${Date.now()}-1`,
          status: 'offer_selected',
          title: 'Order Placed & Offer Confirmed',
          description: `Selected ${offer.pharmacy.name} with ETA ${offer.estimatedDeliveryMinutes} mins`,
          timestamp: Date.now(),
          isCompleted: true,
          isCurrent: true,
        },
        {
          id: `t-${Date.now()}-2`,
          status: 'preparing',
          title: 'Pharmacy Packing & Bill Generation',
          description: 'Pharmacist verifies batch & seals tamper-proof packaging',
          timestamp: 0,
          isCompleted: false,
          isCurrent: false,
        },
        {
          id: `t-${Date.now()}-3`,
          status: 'out_for_delivery',
          title: 'Out for Delivery',
          description: 'Delivery partner on the way to your location',
          timestamp: 0,
          isCompleted: false,
          isCurrent: false,
        },
        {
          id: `t-${Date.now()}-4`,
          status: 'delivered',
          title: 'Delivered',
          description: 'Medicines delivered safely at your doorstep',
          timestamp: 0,
          isCompleted: false,
          isCurrent: false,
        },
      ],
    };

    all.unshift(newOrder);
    return newOrder;
  }

  static async cancelOrder(orderId: string, reason: string): Promise<Order | null> {
    try {
      const response = await apiClient.post<Order>(`/orders/${orderId}/cancel`, { reason });
      if (response.success && response.data) {
        return response.data;
      }
    } catch {
      // fallback
    }

    const all = this.getInitialOrders();
    const order = all.find((o) => o.id === orderId);
    if (order) {
      order.status = 'cancelled';
      order.statusText = 'Cancelled';
      order.statusDescription = `Order was cancelled: ${reason}`;
      order.timeline.push({
        id: `t-cancel-${Date.now()}`,
        status: 'cancelled',
        title: 'Order Cancelled',
        description: reason,
        timestamp: Date.now(),
        isCompleted: true,
        isCurrent: true,
      });
      return { ...order };
    }
    return null;
  }

  private static delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}
